# Generated by Django 4.1.5 on 2023-11-20 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demo',
            name='age',
            field=models.CharField(max_length=255),
        ),
    ]
